//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XnetIT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class assign_engineer
    {
        public int a_id { get; set; }
        public Nullable<int> eng_id { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<System.DateTime> assign_date { get; set; }
        public Nullable<System.TimeSpan> assign_time { get; set; }
    
        public virtual engineer engineer { get; set; }
        public virtual job job { get; set; }

        [NotMapped]
        public List<engineer> engineerCollection { get; set; }
    }
}
