//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XnetIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_ratings
    {
        public int ra_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> e_id { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual engineer engineer { get; set; }
        public virtual user user { get; set; }
    }
}
