//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XnetIT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class item
    {
        public int i_id { get; set; }

        [Required(ErrorMessage = "State is Required")]
        public string i_state { get; set; }

        [Required(ErrorMessage = "Model Number is Required")]
        public string model_number { get; set; }

        [Required(ErrorMessage = "Serial Number is Required")]
        public string serial_number { get; set; }

        public string i_availability { get; set; }
        public string i_status { get; set; }
    }
}
