//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XnetIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.job_ratings = new HashSet<job_ratings>();
        }
    
        public int job_id { get; set; }
        public string title { get; set; }
        public string j_address { get; set; }
        public Nullable<System.DateTime> j_date { get; set; }
        public Nullable<System.TimeSpan> j_time { get; set; }
        public string site_contact { get; set; }
        public string j_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_ratings> job_ratings { get; set; }
    }
}
