//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XnetIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_ratings
    {
        public int r_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> j_id { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<System.DateTime> date_and_time { get; set; }
    
        public virtual job job { get; set; }
        public virtual user user { get; set; }
    }
}
